import { Inter } from "next/font/google";
import { UserProvider } from '@/contexts/UserContext';
import { TabProvider } from '@/contexts/TabContext';
import Header from "@/components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <TabProvider>
            <Header />
            <body>{children}</body>
          </TabProvider>
        </UserProvider>
      </body>
    </html>
  );
}